sudo: required
addons:
        apt:
                packages:
                        - docker-ce
services:
        - docker
language: bash
script:
        - docker version
        - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        - mkdir ~/.docker
        - echo '{"experimental":"enabled"}' | tee ~/.docker/config.json
        - sudo service docker restart

        # build amd64
        - bash -c 'echo "BUILDING FOR AMD64 ARCHITECTURE ---------------------------------------------------------"'
        - docker build --build-arg TAG=amd64-edge -t $DOCKER_USER/$REPO_NAME:amd64-edge .
        # push image
        - . docker_push amd64-edge
        - bash -c 'echo "-----------------------------------------------------------------------------------------"'

        - bash -c 'echo "REGISTERING QEMU FOR CROSS BUILD *********************************************************"'
        # prepare qemu
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset      

        - bash -c 'echo "BUILDING FOR ARHMF ARCHITECTURE ---------------------------------------------------------"'
        # build arm32v7
        - docker build --build-arg TAG=armhf-edge -t $DOCKER_USER/$REPO_NAME:armhf-edge .
        #push image
        - . docker_push armhf-edge
        - bash -c 'echo "-----------------------------------------------------------------------------------------"'
        
        - bash -c 'echo "BUILDING FOR AARCH64 ARCHITECTURE -------------------------------------------------------"'
        # build aarch64
        - docker build --build-arg TAG=aarch64-edge -t $DOCKER_USER/$REPO_NAME:aarch64-edge .
        #push image
        - . docker_push aarch64-edge
        - bash -c 'echo "-----------------------------------------------------------------------------------------"'
        
        - bash -c 'echo "PREPARING MANIFEST -------------- -------------------------------------------------------"'
        - docker manifest create $DOCKER_USER/$REPO_NAME:edge  $DOCKER_USER/$REPO_NAME:amd64-edge $DOCKER_USER/$REPO_NAME:armhf-edge $DOCKER_USER/$REPO_NAME:aarch64-edge
        - docker manifest annotate $DOCKER_USER/$REPO_NAME:edge $DOCKER_USER/$REPO_NAME:amd64-edge --os linux --arch amd64
        - docker manifest annotate $DOCKER_USER/$REPO_NAME:edge $DOCKER_USER/$REPO_NAME:armhf-edge --os linux --arch arm --variant armv6
        - docker manifest annotate $DOCKER_USER/$REPO_NAME:edge $DOCKER_USER/$REPO_NAME:aarch64-edge --os linux --arch arm64 --variant armv8
        - docker manifest push $DOCKER_USER/$REPO_NAME:edge  
        - bash -c 'echo "-----------------------------------------------------------------------------------------"'
