#!/bin/bash
if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
	docker login -u=$DOCKER_USER -p=$DOCKER_PASS
	TAG=`docker run -i --entrypoint=/bin/busybox  $DOCKER_USER/$REPO_NAME:$1 -c 'cat /etc/alpine-release'`
	TAG=$1
	echo 'TAG:  $TAG'
#	docker tag  raxetul/$REPO_NAME raxetul/$REPO_NAME:$TAG
	docker push raxetul/$REPO_NAME:$TAG
fi

